In [3]:
import numpy as np
import pandas as pd

In [19]:
#RAW DATA FROM SCRAPPIN
df= pd.read_csv('/home/gibeon/Desktop/MY/fvldata/STORAGE/clean_data/pTable001.csv')

#df['Pos'] = df.index
#df.reset_index(level=0, inplace=True)

#df['INDX'] = pd.Series(list(range(len(df['Team']))))
df.head()    ####  REMOVE DIFF,one of WDL,

   Pos  Dir           Team  P  W  D  L  GF  GA  DIFF  Points        Season
0    1    0  VL Copenhagen  1  1  0  0   3   1     2       3  Season 12787
1    2    0   VL Amsterdam  1  1  0  0   2   0     2       3  Season 12787
2    3    0      VL Ankara  1  1  0  0   2   0     2       3  Season 12787
3    4    0        VL Kiev  1  1  0  0   3   2     1       3  Season 12787
4    5    0      VL Zagreb  1  1  0  0   2   1     1       3  Season 12787

In [20]:
# df2 = df.set_index(['P', 'Pos'],drop=False)  ##interesing stuff
# df2.head()

In [21]:
#df.head()
df['Team'].unique()

array(['VL Copenhagen', 'VL Amsterdam', 'VL Ankara', 'VL Kiev',
       'VL Zagreb', 'VL Berlin', 'VL Vienna', 'VL Madrid', 'VL Moscow',
       'VL Lisbon', 'VL Prague', 'VL Rome', 'VL Athens', 'VL London',
       'VL Bern', 'VL Paris'], dtype=object)

In [22]:
def teamCoded(S):
    
#     cats=['MADRID', 'AMSTERDAM','BERLIN','LONDON','ROME','OSLO','LISBON','PARIS','BRUSSELS','ATHENS','STOCKHOLM',
#           'COPENHAGEN','VIENNA', 'ANKARA','EDINBURGH','BERN']
    
    cats=['MADRID', 'AMSTERDAM','BERLIN','LONDON','ROME','MOSCOW','LISBON','PARIS','ZAGREB','ATHENS','PRAGUE',
          'COPENHAGEN','VIENNA', 'ANKARA','KIEV','BERN']

    catsRev=[]
    for tm in S:
        if tm == cats[0]:
            catsRev.append(1)
        elif tm == cats[1]:
            catsRev.append(2)
        elif tm == cats[2]:
            catsRev.append(3)
        elif tm == cats[3]:
            catsRev.append(4)
        elif tm == cats[4]:
            catsRev.append(5)
        elif tm == cats[5]:
            catsRev.append(6)
        elif tm == cats[6]:
            catsRev.append(7)
        elif tm == cats[7]:
            catsRev.append(8)
        elif tm == cats[8]:
            catsRev.append(9)
        elif tm == cats[9]:
            catsRev.append(10)
        elif tm == cats[10]:
            catsRev.append(11)
        elif tm == cats[11]:
            catsRev.append(12)
        elif tm == cats[12]:
            catsRev.append(13)
        elif tm == cats[13]:
            catsRev.append(14)
        elif tm == cats[14]:
            catsRev.append(15)
        elif tm == cats[15]:
            catsRev.append(16)
    return catsRev


df['TEAM']=pd.Series([x.split()[1].upper() for x in df.Team])
df['HOMECODE']=teamCoded(df['TEAM'])
df['AWAYCODE']=teamCoded(df['TEAM'])

In [23]:
df.head()

,Pos,Dir,Team,P,W,D,L,GF,GA,DIFF,Points,Season,TEAM,HOMECODE,AWAYCODE
0,1,0,VL Copenhagen,1,1,0,0,3,1,2,3,Season 12787,COPENHAGEN,12,12
1,2,0,VL Amsterdam,1,1,0,0,2,0,2,3,Season 12787,AMSTERDAM,2,2
2,3,0,VL Ankara,1,1,0,0,2,0,2,3,Season 12787,ANKARA,14,14
3,4,0,VL Kiev,1,1,0,0,3,2,1,3,Season 12787,KIEV,15,15
4,5,0,VL Zagreb,1,1,0,0,2,1,1,3,Season 12787,ZAGREB,9,9

In [24]:
df1 = df[df.isna().any(axis=1)]

In [25]:
df1

Empty DataFrame
Columns: [Pos, Dir, Team, P, W, D, L, GF, GA, DIFF, Points, Season, TEAM, HOMECODE, AWAYCODE]
Index: []

In [26]:
dfR= pd.read_csv('/home/gibeon/Desktop/MY/fvldata/STORAGE/clean_data/pResu001.csv')

#dfR= pd.read_csv('/home/ideon/Desktop/DATA CENTRE/resultDataR.csv')
dfR.head()

              TIMER                       TEAMSr   HTR   FTR  P        Season
0  27/07/2019 10:50  VL Copenhagen  -  VL London  2:01  3:01  1  Season 12787
1  27/07/2019 10:50      VL Berlin  -  VL Athens  1:00  1:00  1  Season 12787
2  27/07/2019 10:50      VL Lisbon  -  VL Moscow  0:00  0:00  1  Season 12787
3  27/07/2019 10:50       VL Ankara  -  VL Paris  0:00  2:00  1  Season 12787
4  27/07/2019 10:50        VL Prague  -  VL Kiev  0:03  2:03  1  Season 12787

In [27]:


#function to input(ps) DF column of form/content (3:2) eg HT result or HT results and out put ps.series with eithe 0,1 or 2
def results(ps):

    #ps = ps.dropna()
    lp=[]
    for x in ps:
       # print(x)
        
        h=x.replace(':','  ')[:1]
      #  print(h)
        a=x.replace(':','  ')[1:]
        if float(h) > float(a):
            lp.append(1)

        elif float(a) > float(h):
            lp.append(2)
        else:
            lp.append(0)

    return pd.Series(lp)



def over_under(ps,n):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        if (float(h) + float(a)) > float(n):
            lp.append(1)

        else:
            #means it is under n eg under 2.5
            lp.append(0)

    return pd.Series(lp)

##addition collumn of all goals
def goalsum(ps):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        lp.append((float(h) + float(a)))

    return pd.Series(lp)

In [28]:
#======================================================================
dfR['TEAMSr']
dfR['TEAMSr']=pd.Series([x.upper() for x in dfR.TEAMSr])
dfR['TEAMSr']=pd.Series([x.upper() for x in dfR.TEAMSr])
#split TEAMS into HOME & AWAY 
dfR['HOME']=pd.Series([x.split()[1] for x in dfR.TEAMSr]) 
dfR['AWAY']=pd.Series([x.split()[4] for x in dfR.TEAMSr])

dfR['TIMEr']=pd.Series([x.split()[1] for x in dfR.TIMER])
#Use teamCode FX to code HOME & AWAY collumns and crean new HOMECODE & AWAYCODE
dfR['TC']=dfR['HOME']+' '+dfR['AWAY']

dfR['HOMECODE']=teamCoded(dfR['HOME'])
dfR['AWAYCODE']=teamCoded(dfR['AWAY'])
#dfR['TEAMSC']=dfR['HOMECODE'] + dfR['AWAYCODE']
#teamCode(dfR['HOME'])


    
dfR['FT_Goals']=pd.Series([str(x).replace(':','  ')[:] for x in dfR.FTR])
dfR['HT_Goals']=pd.Series([str(x).replace(':','  ')[:] for x in dfR.HTR])
dfR['FT_home_goals']=pd.Series([str(x).replace(':','  ')[:1] for x in dfR.FTR])
dfR['FT_away_goals']=pd.Series([str(x).replace(':','  ')[1:] for x in dfR.FTR])
dfR['HT_home_goals']=pd.Series([str(x).replace(':','  ')[:1] for x in dfR.HTR])
dfR['HT_away_goals']=pd.Series([str(x).replace(':','  ')[1:] for x in dfR.HTR])



dfR['FT_Results_1_0_2']=results(dfR['FT_Goals'])
dfR['HT_Results_1_0_2']=results(dfR['HT_Goals'])


# FT UNDER /OVER Goals
p = 3.5
n = 2.5
q = 1.5

dfR['Under_Over_3.5']= over_under(dfR['FT_Goals'],p)
dfR['Under_Over_2.5']= over_under(dfR['FT_Goals'],n)
dfR['Under_Over_1.5']= over_under(dfR['FT_Goals'],q)



dfR['Sum_Goals']= goalsum(dfR['FT_Goals'])





dfR['Sum_Goals']= goalsum(dfR['FT_Goals'])# addition column of all goals

#dfR['HT_Results_1_0_2']=results(dfR['HT_Goals'])

colum=['P','Season','TC','HOMECODE', 'AWAYCODE','TIMEr','HTR', 'FTR', 'HT_home_goals', 'HT_away_goals',
       'FT_home_goals','FT_away_goals','Sum_Goals','HT_Results_1_0_2','FT_Results_1_0_2','Under_Over_1.5','Under_Over_2.5',
       'Under_Over_3.5']
resu= dfR.reindex(columns=colum).fillna(0)#.values


colum=['TC','HOMECODE', 'AWAYCODE','TIMEr','HTR', 'FTR', 'HT_home_goals', 'HT_away_goals',
       'FT_home_goals','FT_away_goals','HT_Results_1_0_2','FT_Results_1_0_2','TIMER','TIMED','1','2','X','HT1','HT2','HTX','FS (0:0)','FS(0:0)2','FS(0:0)X','G(0.5)O','G(0.5)U',
         'G(1.5)O','G(1.5)U','G(2.5)O','G(2.5)U','G(3.5)O','G(3.5)U','G(4.5)O','G(4.5)U','Under_Over_1.5','Under_Over_2.5',
       'Under_Over_3.5']

In [29]:
resu.head()

,P,Season,TC,HOMECODE,AWAYCODE,TIMEr,HTR,FTR,HT_home_goals,HT_away_goals,FT_home_goals,FT_away_goals,Sum_Goals,HT_Results_1_0_2,FT_Results_1_0_2,Under_Over_1.5,Under_Over_2.5,Under_Over_3.5
0,1,Season 12787,COPENHAGEN LONDON,12,4,10:50,2:01,3:01,2,01,3,01,4.0,1,1,1,1,1
1,1,Season 12787,BERLIN ATHENS,3,10,10:50,1:00,1:00,1,00,1,00,1.0,1,1,0,0,0
2,1,Season 12787,LISBON MOSCOW,7,6,10:50,0:00,0:00,0,00,0,00,0.0,0,0,0,0,0
3,1,Season 12787,ANKARA PARIS,14,8,10:50,0:00,2:00,0,00,2,00,2.0,0,1,1,0,0
4,1,Season 12787,PRAGUE KIEV,11,15,10:50,0:03,2:03,0,03,2,03,5.0,2,2,1,1,1

In [30]:
df.iloc[20:600, :20]

,Pos,Dir,Team,P,W,D,L,GF,GA,DIFF,Points,Season,TEAM,HOMECODE,AWAYCODE
20,5,1,VL Amsterdam,2,1,0,1,2,1,1,3,Season 12787,AMSTERDAM,2,2
21,6,1,VL Ankara,2,1,0,1,2,1,1,3,Season 12787,ANKARA,14,14
22,7,1,VL Kiev,2,1,0,1,3,3,0,3,Season 12787,KIEV,15,15
23,8,-1,VL Prague,2,1,0,1,3,3,0,3,Season 12787,PRAGUE,11,11
24,9,-1,VL Athens,2,1,0,1,1,1,0,3,Season 12787,ATHENS,10,10
25,10,1,VL Berlin,2,1,0,1,2,3,-1,3,Season 12787,BERLIN,3,3
26,11,1,VL Zagreb,2,1,0,1,2,4,-2,3,Season 12787,ZAGREB,9,9
27,12,1,VL Madrid,2,0,2,0,3,3,0,2,Season 12787,MADRID,1,1
28,13,1,VL Rome,2,0,1,1,1,2,-1,1,Season 12787,ROME,5,5
29,14,1,VL Lisbon,2,0,1,1,0,1,-1,1,Season 12787,LISBON,7,7
30,15,1,VL London,2,0,1,1,2,4,-2,1,Season 12787,LONDON,4,4
31,16,1,VL Bern,2,0,1,1,0,2,-2,1,Season 12787,BERN,16,16
32,1,0,VL Copenhagen,3,3,0,0,5,1,4,9,Season 12787,COPENHAGEN,12,12
33,2,-1,VL Ankara,3,2,0,1,3,1,2,6,Season 12787,ANKARA,14,14
34,3,-1,VL Madrid,3,1,2,0,9,3,6,5,Season 12787,MADRID,1,1
35,4,1,VL Vienna,3,1,2,0,4,3,1,5,Season 12787,VIENNA,13,13
36,5,1,VL Moscow,3,1,1,1,3,2,1,4,Season 12787,MOSCOW,6,6
37,6,-1,VL Rome,3,1,1,1,2,2,0,4,Season 12787,ROME,5,5
38,7,-1,VL Bern,3,1,1,1,2,2,0,4,Season 12787,BERN,16,16
39,8,-1,VL Athens,3,1,1,1,1,1,0,4,Season 12787,ATHENS,10,10
40,9,-1,VL London,3,1,1,1,3,4,-1,4,Season 12787,LONDON,4,4
41,10,0,VL Berlin,3,1,1,1,3,4,-1,4,Season 12787,BERLIN,3,3
42,11,0,VL Zagreb,3,1,1,1,2,4,-2,4,Season 12787,ZAGREB,9,9
43,12,1,VL Amsterdam,3,1,0,2,2,2,0,3,Season 12787,AMSTERDAM,2,2
44,13,1,VL Prague,3,1,0,2,3,4,-1,3,Season 12787,PRAGUE,11,11
45,14,1,VL Paris,3,1,0,2,3,4,-1,3,Season 12787,PARIS,8,8
46,15,1,VL Kiev,3,1,0,2,3,9,-6,3,Season 12787,KIEV,15,15
47,16,1,VL Lisbon,3,0,1,2,0,2,-2,1,Season 12787,LISBON,7,7
48,1,0,VL Copenhagen,4,3,1,0,5,1,4,10,Season 12787,COPENHAGEN,12,12
49,2,-1,VL Moscow,4,2,1,1,5,2,3,7,Season 12787,MOSCOW,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,11,1,VL Bern,28,10,3,15,25,43,-18,33,Season 12786,BERN,16,16
571,12,-1,VL Vienna,28,8,7,13,30,42,-12,31,Season 12786,VIENNA,13,13
572,13,1,VL Athens,28,6,11,11,29,38,-9,29,Season 12786,ATHENS,10,10
573,14,0,VL Ankara,28,6,8,14,35,44,-9,26,Season 12786,ANKARA,14,14
574,15,0,VL Prague,28,7,4,17,31,60,-29,25,Season 12786,PRAGUE,11,11
575,16,0,VL Kiev,28,5,5,18,36,65,-29,20,Season 12786,KIEV,15,15
576,1,-1,VL Berlin,29,18,4,7,56,32,24,58,Season 12786,BERLIN,3,3
577,2,1,VL Madrid,29,16,9,4,49,24,25,57,Season 12786,MADRID,1,1
578,3,0,VL London,29,15,7,7,49,25,24,52,Season 12786,LONDON,4,4
579,4,-1,VL Amsterdam,29,13,8,8,41,22,19,47,Season 12786,AMSTERDAM,2,2
580,5,-1,VL Rome,29,13,8,8,47,32,15,47,Season 12786,ROME,5,5
581,6,1,VL Lisbon,29,14,5,10,43,36,7,47,Season 12786,LISBON,7,7
582,7,0,VL Moscow,29,12,8,9,48,45,3,44,Season 12786,MOSCOW,6,6
583,8,0,VL Zagreb,29,11,9,9,33,35,-2,42,Season 12786,ZAGREB,9,9
584,9,0,VL Paris,29,9,13,7,41,36,5,40,Season 12786,PARIS,8,8
585,10,0,VL Copenhagen,29,9,8,12,28,36,-8,35,Season 12786,COPENHAGEN,12,12
586,11,0,VL Bern,29,10,3,16,25,47,-22,33,Season 12786,BERN,16,16
587,12,0,VL Vienna,29,8,7,14,30,43,-13,31,Season 12786,VIENNA,13,13
588,13,0,VL Athens,29,6,11,12,30,40,-10,29,Season 12786,ATHENS,10,10
589,14,0,VL Ankara,29,6,8,15,35,47,-12,26,Season 12786,ANKARA,14,14
590,15,0,VL Prague,29,7,5,17,33,62,-29,26,Season 12786,PRAGUE,11,11
591,16,0,VL Kiev,29,6,5,18,39,65,-26,23,Season 12786,KIEV,15,15
592,1,0,VL Berlin,30,19,4,7,58,32,26,61,Season 12786,BERLIN,3,3
593,2,0,VL Madrid,30,16,10,4,49,24,25,58,Season 12786,MADRID,1,1
594,3,0,VL London,30,16,7,7,51,26,25,55,Season 12786,LONDON,4,4
595,4,0,VL Amsterdam,30,14,8,8,43,23,20,50,Season 12786,AMSTERDAM,2,2
596,5,-1,VL Lisbon,30,15,5,10,45,37,8,50,Season 12786,LISBON,7,7
597,6,1,VL Rome,30,13,9,8,47,32,15,48,Season 12786,ROME,5,5
598,7,0,VL Moscow,30,12,9,9,49,46,3,45,Season 12786,MOSCOW,6,6
599,8,0,VL Zagreb,30,11,9,10,34,37,-3,42,Season 12786,ZAGREB,9,9

In [31]:
df.iloc[:50, 1:4][df.TEAM == 'MADRID']

/home/gibeon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

    Dir       Team  P
7     0  VL Madrid  1
27    1  VL Madrid  2
34   -1  VL Madrid  3

In [32]:
for seas in df.Season.unique():
    dfaa= df[df.Season == seas]
    print(dfaa)
    break
    
    
#     for block in df[df.Season == seas]:
#         print(block)

     Pos  Dir           Team  P  W  D  L  GF  GA  DIFF  Points        Season  \
0      1    0  VL Copenhagen  1  1  0  0   3   1     2       3  Season 12787
1      2    0   VL Amsterdam  1  1  0  0   2   0     2       3  Season 12787
2      3    0      VL Ankara  1  1  0  0   2   0     2       3  Season 12787
3      4    0        VL Kiev  1  1  0  0   3   2     1       3  Season 12787
4      5    0      VL Zagreb  1  1  0  0   2   1     1       3  Season 12787
5      6    0      VL Berlin  1  1  0  0   1   0     1       3  Season 12787
6      7    0      VL Vienna  1  0  1  0   2   2     0       1  Season 12787
7      8    0      VL Madrid  1  0  1  0   2   2     0       1  Season 12787
8      9    0      VL Moscow  1  0  1  0   0   0     0       1  Season 12787
9     10    0      VL Lisbon  1  0  1  0   0   0     0       1  Season 12787
10    11    0      VL Prague  1  0  0  1   2   3    -1       0  Season 12787
11    12    0        VL Rome  1  0  0  1   1   2    -1       0  Season 12787
12    13    0      VL Athens  1  0  0  1   0   1    -1       0  Season 12787
13    14    0      VL London  1  0  0  1   1   3    -2       0  Season 12787
14    15    0        VL Bern  1  0  0  1   0   2    -2       0  Season 12787
15    16    0       VL Paris  1  0  0  1   0   2    -2       0  Season 12787
16     1    0  VL Copenhagen  2  2  0  0   4   1     3       6  Season 12787
17     2   -1      VL Moscow  2  1  1  0   3   1     2       4  Season 12787
18     3   -1      VL Vienna  2  1  1  0   3   2     1       4  Season 12787
19     4   -1       VL Paris  2  1  0  1   3   2     1       3  Season 12787
20     5    1   VL Amsterdam  2  1  0  1   2   1     1       3  Season 12787
21     6    1      VL Ankara  2  1  0  1   2   1     1       3  Season 12787
22     7    1        VL Kiev  2  1  0  1   3   3     0       3  Season 12787
23     8   -1      VL Prague  2  1  0  1   3   3     0       3  Season 12787
24     9   -1      VL Athens  2  1  0  1   1   1     0       3  Season 12787
25    10    1      VL Berlin  2  1  0  1   2   3    -1       3  Season 12787
26    11    1      VL Zagreb  2  1  0  1   2   4    -2       3  Season 12787
27    12    1      VL Madrid  2  0  2  0   3   3     0       2  Season 12787
28    13    1        VL Rome  2  0  1  1   1   2    -1       1  Season 12787
29    14    1      VL Lisbon  2  0  1  1   0   1    -1       1  Season 12787
..   ...  ...            ... .. .. .. ..  ..  ..   ...     ...           ...
98     3   -1      VL Madrid  7  3  3  1  16  10     6      12  Season 12787
99     4    1      VL Ankara  7  3  3  1   8   5     3      12  Season 12787
100    5    1      VL London  7  3  2  2   9   6     3      11  Season 12787
101    6    1  VL Copenhagen  7  3  2  2   7   6     1      11  Season 12787
102    7   -1      VL Vienna  7  2  4  1   6   5     1      10  Season 12787
103    8   -1   VL Amsterdam  7  3  1  3   5   6    -1      10  Season 12787
104    9    1      VL Athens  7  2  2  3   5   5     0       8  Season 12787
105   10    1        VL Rome  7  2  2  3   7   8    -1       8  Season 12787
106   11   -1        VL Bern  7  2  2  3   5   9    -4       8  Season 12787
107   12   -1        VL Kiev  7  2  2  3   8  13    -5       8  Season 12787
108   13   -1      VL Prague  7  2  1  4  14  14     0       7  Season 12787
109   14    1      VL Lisbon  7  2  1  4   5   7    -2       7  Season 12787
110   15   -1      VL Zagreb  7  1  3  3   3   9    -6       6  Season 12787
111   16    1       VL Paris  7  1  2  4   6  11    -5       5  Season 12787
112    1    0      VL Moscow  8  5  2  1  13   4     9      17  Season 12787
113    2    0      VL Berlin  8  5  1  2  11   9     2      16  Season 12787
114    3   -1      VL London  8  4  2  2  11   7     4      14  Season 12787
115    4    0      VL Ankara  8  3  4  1   9   6     3      13  Season 12787
116    5   -1      VL Vienna  8  3  4  1   7   5     2      13  Season 12787
117    6   -1   VL Amsterdam  8  4  1  3   7   7     0      13  Season 12787
118    7    1      VL Madrid  8  3  3  2  16  11     5      12  Season 12787
119    8    1  VL Copenhagen  8  3  3  2   8   7     1      12  Season 12787
120    9   -1        VL Bern  8  3  2  3   9  10    -1      11  Season 12787
121   10   -1      VL Prague  8  3  1  4  15  14     1      10  Season 12787
122   11    1      VL Athens  8  2  3  3   6   6     0       9  Season 12787
123   12    1        VL Rome  8  2  2  4   8  10    -2       8  Season 12787
124   13    1        VL Kiev  8  2  2  4   9  17    -8       8  Season 12787
125   14    0      VL Lisbon  8  2  1  5   6   9    -3       7  Season 12787
126   15    0      VL Zagreb  8  1  3  4   3  10    -7       6  Season 12787
127   16    0       VL Paris  8  1  2  5   6  12    -6       5  Season 12787

           TEAM  HOMECODE  AWAYCODE
0    COPENHAGEN        12        12
1     AMSTERDAM         2         2
2        ANKARA        14        14
3          KIEV        15        15
4        ZAGREB         9         9
5        BERLIN         3         3
6        VIENNA        13        13
7        MADRID         1         1
8        MOSCOW         6         6
9        LISBON         7         7
10       PRAGUE        11        11
11         ROME         5         5
12       ATHENS        10        10
13       LONDON         4         4
14         BERN        16        16
15        PARIS         8         8
16   COPENHAGEN        12        12
17       MOSCOW         6         6
18       VIENNA        13        13
19        PARIS         8         8
20    AMSTERDAM         2         2
21       ANKARA        14        14
22         KIEV        15        15
23       PRAGUE        11        11
24       ATHENS        10        10
25       BERLIN         3         3
26       ZAGREB         9         9
27       MADRID         1         1
28         ROME         5         5
29       LISBON         7         7
..          ...       ...       ...
98       MADRID         1         1
99       ANKARA        14        14
100      LONDON         4         4
101  COPENHAGEN        12        12
102      VIENNA        13        13
103   AMSTERDAM         2         2
104      ATHENS        10        10
105        ROME         5         5
106        BERN        16        16
107        KIEV        15        15
108      PRAGUE        11        11
109      LISBON         7         7
110      ZAGREB         9         9
111       PARIS         8         8
112      MOSCOW         6         6
113      BERLIN         3         3
114      LONDON         4         4
115      ANKARA        14        14
116      VIENNA        13        13
117   AMSTERDAM         2         2
118      MADRID         1         1
119  COPENHAGEN        12        12
120        BERN        16        16
121      PRAGUE        11        11
122      ATHENS        10        10
123        ROME         5         5
124        KIEV        15        15
125      LISBON         7         7
126      ZAGREB         9         9
127       PARIS         8         8

[128 rows x 15 columns]

In [33]:
df[df.Season == "Season 12628"][df.P == 1][df.TEAM == "LISBON"] # Amazing filter

/home/gibeon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,Pos,Dir,Team,P,W,D,L,GF,GA,DIFF,Points,Season,TEAM,HOMECODE,AWAYCODE
27328,1,0,VL Lisbon,1,1,0,0,3,0,3,3,Season 12628,LISBON,7,7

In [34]:
df.iloc[:, 1:40][df.Dir <5]

,Dir,Team,P,W,D,L,GF,GA,DIFF,Points,Season,TEAM,HOMECODE,AWAYCODE
0,0,VL Copenhagen,1,1,0,0,3,1,2,3,Season 12787,COPENHAGEN,12,12
1,0,VL Amsterdam,1,1,0,0,2,0,2,3,Season 12787,AMSTERDAM,2,2
2,0,VL Ankara,1,1,0,0,2,0,2,3,Season 12787,ANKARA,14,14
3,0,VL Kiev,1,1,0,0,3,2,1,3,Season 12787,KIEV,15,15
4,0,VL Zagreb,1,1,0,0,2,1,1,3,Season 12787,ZAGREB,9,9
5,0,VL Berlin,1,1,0,0,1,0,1,3,Season 12787,BERLIN,3,3
6,0,VL Vienna,1,0,1,0,2,2,0,1,Season 12787,VIENNA,13,13
7,0,VL Madrid,1,0,1,0,2,2,0,1,Season 12787,MADRID,1,1
8,0,VL Moscow,1,0,1,0,0,0,0,1,Season 12787,MOSCOW,6,6
9,0,VL Lisbon,1,0,1,0,0,0,0,1,Season 12787,LISBON,7,7
10,0,VL Prague,1,0,0,1,2,3,-1,0,Season 12787,PRAGUE,11,11
11,0,VL Rome,1,0,0,1,1,2,-1,0,Season 12787,ROME,5,5
12,0,VL Athens,1,0,0,1,0,1,-1,0,Season 12787,ATHENS,10,10
13,0,VL London,1,0,0,1,1,3,-2,0,Season 12787,LONDON,4,4
14,0,VL Bern,1,0,0,1,0,2,-2,0,Season 12787,BERN,16,16
15,0,VL Paris,1,0,0,1,0,2,-2,0,Season 12787,PARIS,8,8
16,0,VL Copenhagen,2,2,0,0,4,1,3,6,Season 12787,COPENHAGEN,12,12
17,-1,VL Moscow,2,1,1,0,3,1,2,4,Season 12787,MOSCOW,6,6
18,-1,VL Vienna,2,1,1,0,3,2,1,4,Season 12787,VIENNA,13,13
19,-1,VL Paris,2,1,0,1,3,2,1,3,Season 12787,PARIS,8,8
20,1,VL Amsterdam,2,1,0,1,2,1,1,3,Season 12787,AMSTERDAM,2,2
21,1,VL Ankara,2,1,0,1,2,1,1,3,Season 12787,ANKARA,14,14
22,1,VL Kiev,2,1,0,1,3,3,0,3,Season 12787,KIEV,15,15
23,-1,VL Prague,2,1,0,1,3,3,0,3,Season 12787,PRAGUE,11,11
24,-1,VL Athens,2,1,0,1,1,1,0,3,Season 12787,ATHENS,10,10
25,1,VL Berlin,2,1,0,1,2,3,-1,3,Season 12787,BERLIN,3,3
26,1,VL Zagreb,2,1,0,1,2,4,-2,3,Season 12787,ZAGREB,9,9
27,1,VL Madrid,2,0,2,0,3,3,0,2,Season 12787,MADRID,1,1
28,1,VL Rome,2,0,1,1,1,2,-1,1,Season 12787,ROME,5,5
29,1,VL Lisbon,2,0,1,1,0,1,-1,1,Season 12787,LISBON,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27778,0,VL Amsterdam,29,17,5,7,51,33,18,56,Season 12628,AMSTERDAM,2,2
27779,0,VL Lisbon,29,17,5,7,43,25,18,56,Season 12628,LISBON,7,7
27780,0,VL Rome,29,16,3,10,49,37,12,51,Season 12628,ROME,5,5
27781,-1,VL Zagreb,29,12,11,6,39,27,12,47,Season 12628,ZAGREB,9,9
27782,1,VL Moscow,29,13,7,9,41,29,12,46,Season 12628,MOSCOW,6,6
27783,-1,VL London,29,12,4,13,43,38,5,40,Season 12628,LONDON,4,4
27784,1,VL Prague,29,11,6,12,39,46,-7,39,Season 12628,PRAGUE,11,11
27785,0,VL Ankara,29,12,2,15,34,42,-8,38,Season 12628,ANKARA,14,14
27786,0,VL Bern,29,8,6,15,36,49,-13,30,Season 12628,BERN,16,16
27787,0,VL Paris,29,7,8,14,35,47,-12,29,Season 12628,PARIS,8,8
27788,-1,VL Athens,29,8,4,17,29,54,-25,28,Season 12628,ATHENS,10,10
27789,1,VL Kiev,29,8,3,18,38,56,-18,27,Season 12628,KIEV,15,15
27790,0,VL Vienna,29,7,5,17,21,43,-22,26,Season 12628,VIENNA,13,13
27791,0,VL Copenhagen,29,7,4,18,19,42,-23,25,Season 12628,COPENHAGEN,12,12
27792,0,VL Berlin,30,20,3,7,54,29,25,63,Season 12628,BERLIN,3,3
27793,0,VL Madrid,30,17,8,5,63,33,30,59,Season 12628,MADRID,1,1
27794,0,VL Amsterdam,30,18,5,7,54,33,21,59,Season 12628,AMSTERDAM,2,2
27795,0,VL Lisbon,30,18,5,7,44,25,19,59,Season 12628,LISBON,7,7
27796,0,VL Rome,30,17,3,10,52,38,14,54,Season 12628,ROME,5,5
27797,0,VL Zagreb,30,12,11,7,39,28,11,47,Season 12628,ZAGREB,9,9
27798,0,VL Moscow,30,13,7,10,42,32,10,46,Season 12628,MOSCOW,6,6
27799,0,VL London,30,12,5,13,45,40,5,41,Season 12628,LONDON,4,4
27800,0,VL Prague,30,11,6,13,39,48,-9,39,Season 12628,PRAGUE,11,11
27801,0,VL Ankara,30,12,2,16,34,45,-11,38,Season 12628,ANKARA,14,14
27802,-1,VL Paris,30,8,8,14,37,47,-10,32,Season 12628,PARIS,8,8
27803,1,VL Bern,30,8,7,15,37,50,-13,31,Season 12628,BERN,16,16
27804,0,VL Athens,30,8,5,17,30,55,-25,29,Season 12628,ATHENS,10,10
27805,0,VL Kiev,30,8,4,18,40,58,-18,28,Season 12628,KIEV,15,15
27806,0,VL Vienna,30,7,5,18,21,46,-25,26,Season 12628,VIENNA,13,13
27807,0,VL Copenhagen,30,7,4,19,19,43,-24,25,Season 12628,COPENHAGEN,12,12

In [35]:
def gen_dir(ps):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        lp.append((float(h) + float(a)))

    return pd.Series(lp)

In [36]:
df['Sum_Goals']= gendir(df['Dir'])

NameError: name 'gendir' is not defined

In [37]:
df[df.Season == df.Season.unique()[2]]

,Pos,Dir,Team,P,W,D,L,GF,GA,DIFF,Points,Season,TEAM,HOMECODE,AWAYCODE
608,1,0,VL Amsterdam,1,1,0,0,3,0,3,3,Season 12785,AMSTERDAM,2,2
609,2,0,VL London,1,1,0,0,2,0,2,3,Season 12785,LONDON,4,4
610,3,0,VL Kiev,1,1,0,0,1,0,1,3,Season 12785,KIEV,15,15
611,4,0,VL Madrid,1,1,0,0,1,0,1,3,Season 12785,MADRID,1,1
612,5,0,VL Berlin,1,1,0,0,1,0,1,3,Season 12785,BERLIN,3,3
613,6,0,VL Lisbon,1,1,0,0,1,0,1,3,Season 12785,LISBON,7,7
614,7,0,VL Copenhagen,1,1,0,0,1,0,1,3,Season 12785,COPENHAGEN,12,12
615,8,0,VL Athens,1,0,1,0,0,0,0,1,Season 12785,ATHENS,10,10
616,9,0,VL Vienna,1,0,1,0,0,0,0,1,Season 12785,VIENNA,13,13
617,10,0,VL Prague,1,0,0,1,0,1,-1,0,Season 12785,PRAGUE,11,11
618,11,0,VL Moscow,1,0,0,1,0,1,-1,0,Season 12785,MOSCOW,6,6
619,12,0,VL Ankara,1,0,0,1,0,1,-1,0,Season 12785,ANKARA,14,14
620,13,0,VL Zagreb,1,0,0,1,0,1,-1,0,Season 12785,ZAGREB,9,9
621,14,0,VL Paris,1,0,0,1,0,1,-1,0,Season 12785,PARIS,8,8
622,15,0,VL Bern,1,0,0,1,0,2,-2,0,Season 12785,BERN,16,16
623,16,0,VL Rome,1,0,0,1,0,3,-3,0,Season 12785,ROME,5,5
624,1,-1,VL Madrid,2,2,0,0,4,0,4,6,Season 12785,MADRID,1,1
625,2,-1,VL Berlin,2,2,0,0,3,1,2,6,Season 12785,BERLIN,3,3
626,3,0,VL Kiev,2,2,0,0,2,0,2,6,Season 12785,KIEV,15,15
627,4,-1,VL Copenhagen,2,2,0,0,2,0,2,6,Season 12785,COPENHAGEN,12,12
628,5,1,VL Amsterdam,2,1,1,0,3,0,3,4,Season 12785,AMSTERDAM,2,2
629,6,1,VL London,2,1,1,0,4,2,2,4,Season 12785,LONDON,4,4
630,7,1,VL Lisbon,2,1,1,0,3,2,1,4,Season 12785,LISBON,7,7
631,8,-1,VL Rome,2,1,0,1,4,4,0,3,Season 12785,ROME,5,5
632,9,-1,VL Zagreb,2,1,0,1,1,1,0,3,Season 12785,ZAGREB,9,9
633,10,1,VL Athens,2,0,1,1,0,1,-1,1,Season 12785,ATHENS,10,10
634,11,1,VL Prague,2,0,1,1,0,1,-1,1,Season 12785,PRAGUE,11,11
635,12,1,VL Vienna,2,0,1,1,0,1,-1,1,Season 12785,VIENNA,13,13
636,13,1,VL Moscow,2,0,0,2,0,2,-2,0,Season 12785,MOSCOW,6,6
637,14,-1,VL Bern,2,0,0,2,1,4,-3,0,Season 12785,BERN,16,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1058,3,1,VL London,29,14,8,7,56,31,25,50,Season 12785,LONDON,4,4
1059,4,0,VL Rome,29,13,9,7,65,41,24,48,Season 12785,ROME,5,5
1060,5,0,VL Amsterdam,29,14,5,10,50,37,13,47,Season 12785,AMSTERDAM,2,2
1061,6,0,VL Paris,29,14,5,10,48,40,8,47,Season 12785,PARIS,8,8
1062,7,-1,VL Lisbon,29,13,7,9,39,31,8,46,Season 12785,LISBON,7,7
1063,8,1,VL Athens,29,13,4,12,41,35,6,43,Season 12785,ATHENS,10,10
1064,9,-1,VL Moscow,29,11,8,10,42,40,2,41,Season 12785,MOSCOW,6,6
1065,10,1,VL Zagreb,29,11,8,10,28,28,0,41,Season 12785,ZAGREB,9,9
1066,11,0,VL Kiev,29,11,4,14,38,57,-19,37,Season 12785,KIEV,15,15
1067,12,0,VL Ankara,29,10,6,13,40,47,-7,36,Season 12785,ANKARA,14,14
1068,13,0,VL Prague,29,7,7,15,30,50,-20,28,Season 12785,PRAGUE,11,11
1069,14,0,VL Copenhagen,29,6,7,16,19,37,-18,25,Season 12785,COPENHAGEN,12,12
1070,15,0,VL Bern,29,5,7,17,30,62,-32,22,Season 12785,BERN,16,16
1071,16,0,VL Vienna,29,4,9,16,15,40,-25,21,Season 12785,VIENNA,13,13
1072,1,0,VL Madrid,30,19,6,5,62,36,26,63,Season 12785,MADRID,1,1
1073,2,-1,VL London,30,15,8,7,58,32,26,53,Season 12785,LONDON,4,4
1074,3,1,VL Berlin,30,16,4,10,47,38,9,52,Season 12785,BERLIN,3,3
1075,4,-1,VL Amsterdam,30,15,5,10,51,37,14,50,Season 12785,AMSTERDAM,2,2
1076,5,1,VL Rome,30,13,10,7,66,42,24,49,Season 12785,ROME,5,5
1077,6,-1,VL Lisbon,30,13,8,9,40,32,8,47,Season 12785,LISBON,7,7
1078,7,1,VL Paris,30,14,5,11,48,41,7,47,Season 12785,PARIS,8,8
1079,8,0,VL Athens,30,14,4,12,45,37,8,46,Season 12785,ATHENS,10,10
1080,9,0,VL Moscow,30,12,8,10,44,41,3,44,Season 12785,MOSCOW,6,6
1081,10,0,VL Zagreb,30,11,9,10,28,28,0,42,Season 12785,ZAGREB,9,9
1082,11,0,VL Kiev,30,11,5,14,38,57,-19,38,Season 12785,KIEV,15,15
1083,12,0,VL Ankara,30,10,6,14,41,49,-8,36,Season 12785,ANKARA,14,14
1084,13,0,VL Prague,30,7,7,16,32,54,-22,28,Season 12785,PRAGUE,11,11
1085,14,0,VL Copenhagen,30,6,7,17,19,38,-19,25,Season 12785,COPENHAGEN,12,12
1086,15,-1,VL Vienna,30,5,9,16,16,40,-24,24,Season 12785,VIENNA,13,13
1087,16,1,VL Bern,30,5,7,18,31,64,-33,22,Season 12785,BERN,16,16

In [38]:
teamDf = df[df.Season == df.Season.unique()[0]][df.TEAM =='BERLIN']

/home/gibeon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [39]:
teamDf

,Pos,Dir,Team,P,W,D,L,GF,GA,DIFF,Points,Season,TEAM,HOMECODE,AWAYCODE
5,6,0,VL Berlin,1,1,0,0,1,0,1,3,Season 12787,BERLIN,3,3
25,10,1,VL Berlin,2,1,0,1,2,3,-1,3,Season 12787,BERLIN,3,3
41,10,0,VL Berlin,3,1,1,1,3,4,-1,4,Season 12787,BERLIN,3,3
61,14,1,VL Berlin,4,1,1,2,3,7,-4,4,Season 12787,BERLIN,3,3
72,9,-1,VL Berlin,5,2,1,2,5,7,-2,7,Season 12787,BERLIN,3,3
84,5,-1,VL Berlin,6,3,1,2,8,9,-1,10,Season 12787,BERLIN,3,3
97,2,-1,VL Berlin,7,4,1,2,10,9,1,13,Season 12787,BERLIN,3,3
113,2,0,VL Berlin,8,5,1,2,11,9,2,16,Season 12787,BERLIN,3,3

In [40]:
for n in range(len(teamDf.Pos)):
    lzz =[]
    dfzz =teamDf[teamDf.P ==n].P
    for dzz in dfzz:
        #if dzz == n:
            print(dzz)
        #else:
            #print('Nope')

1
2
3
4
5
6
7

In [41]:
def gen_dir(ps):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        lp.append((float(h) + float(a)))

    return pd.Series(lp)

In [42]:
for n in range(len(teamDf.Pos)):
    lzz =[]
    if teamDf.
    print(n+1)

SyntaxError: invalid syntax (<ipython-input-42-756488013ea0>, line 3)

In [43]:
#gr = resu.groupby([resu['HOMECODE'], resu['AWAYCODE']])

In [ ]:
#gr # what the f*ck is this pandas object

In [ ]:
df['P']=df['P']+1

In [ ]:
df.head()

In [ ]:
##magic happens here

dff1 = pd.merge(df,resu, on =('Season','P','HOMECODE'))#,by='Season')#,left_on='lkey', right_on='rkey')
#dff1['AWAYCODE'] = dff1['AWAYCODE_x']
dff2 = pd.merge(df,resu, on =('Season','P','AWAYCODE'))#,left_on='lkey', right_on='rkey')

In [ ]:
dff1.sort_values(by=['Season','P'])
dff1 = dff1.drop_duplicates()
dff1.head()

In [ ]:
dff2.sort_values(by=['Season','P'])
dff2 = dff2.drop_duplicates()
dff2.head()

In [ ]:
#dff1.iloc[:, 1:82]#[dff1.TEAM == 'MADRID']  #  most IMPORTANT FILTER OF DFS....NOTE NOTE NOTE
#len(dff1.columns)#[data.three > 5]
#len(dff1.columns)

dff1.iloc[:, 1:20]#[dff1.TEAM == 'MADRID']

In [ ]:
#dff2.iloc[:, 31:52]#[data.three > 5]
#len(dff1.columns)
dff2['HOMECODE'] = dff2['HOMECODE_y']#//couse by duplicate files
#dff2.iloc[:, 1:82]#[dff2.TEAM == 'VIENNA']

In [ ]:
datag = pd.merge(dff1,dff2, on =('Season','P','HOMECODE'))

In [ ]:
datag.sort_values(by=['Season','P'])
datag = datag.drop_duplicates()
datag

In [ ]:
datag.head()

In [ ]:
datag.columns

colt = ['Season','TC_x','HOMECODE','AWAYCODE','TEAM_x','Team_x','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','TEAM_y','Team_y','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','HTR_y',
       'FTR_y', 'HT_home_goals_y', 'HT_away_goals_y', 'FT_home_goals_y',
       'FT_away_goals_y', 'Sum_Goals_y', 'HT_Results_1_0_2_y',
       'FT_Results_1_0_2_y', 'Under_Over_1.5_y', 'Under_Over_2.5_y',
       'Under_Over_3.5_y']

col2 = ['HOMECODE','AWAYCODE','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','Under_Over_2.5_y',]

predict1x2 = ['HOMECODE','AWAYCODE','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','FT_Results_1_0_2_y',]
datag.columns

In [ ]:
#change collum to change what to predict
datag2 =  datag.reindex(columns= col2)
#datag2.iloc[:, 1:38].head()#[dff2.TEAM == 'VIENNA']
datag2.head()

In [ ]:
#datag2.iloc[40:140, 1:38]#.head()#[dff2.TEAM == 'VIENNA']

In [ ]:
#with open('/home/ideon/Desktop/datag5.csv', 'a') as f:
  #  datag.to_csv(f, index=False, header=True)

In [ ]:
mod_data=datag2.reindex(columns=col2).fillna(0)

In [ ]:
mod_data.head()

In [ ]:
t=datag2.shape[0]  # # t is the number of raws
t

In [ ]:
#mod_data
dataR=mod_data.values
dataR

In [ ]:
p1=dataR   # Uncomment when manual is used
p1

In [ ]:
X, y = p1[:,:21],p1[:,21:]

In [ ]:
X = X.reshape(p1.shape[0], 21)
#X = X.astype('float32')

#X = X/60
#X

In [ ]:
X.shape

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
y_train

In [ ]:
y_test

In [ ]:
# from keras.utils import np_utils
# NB_CLASSES =1
# import numpy as np
# y_train = np_utils.to_categorical(y_train, NB_CLASSES)
# y_test = np_utils.to_categorical(y_test, NB_CLASSES)

In [ ]:
y_train

In [ ]:
y_test

In [ ]:
from __future__ import print_function
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD,Adam
from keras.utils import np_utils
import numpy as np
import pylab as plt
import numpy as np
import matplotlib.pyplot as plt
import os

In [ ]:
#X_train, X_test, y_train, y_test
#
X_train = X_train.reshape(X_train.shape[0], 21)
X_test = X_test.reshape(X_test.shape[0], 21)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
# normalize
X_train /= 50
X_test /= 50

In [ ]:
X_train.shape

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
y_test

In [ ]:
y_train

In [ ]:
NB_EPOCH = 30
BATCH_SIZE = 30
VERBOSE = 1
NB_CLASSES = 1 # number of outputs = number of digits
OPTIMIZER =Adam() #SGD() 
N_HIDDEN0 = 60
N_HIDDEN1 =160
N_HIDDEN2 =500
N_HIDDEN3 =160
VALIDATION_SPLIT=0.2 # how much TRAIN is reserved for VALIDATION
DROPOUT = 0.01
RESHAPED = 21

In [ ]:

# M_HIDDEN hidden layers 10 outputs
model = Sequential()
model.add(Dense(N_HIDDEN0, input_shape=(RESHAPED,)))
model.add(Activation('relu'))
model.add(Dropout(DROPOUT))
model.add(Dense(N_HIDDEN1))
model.add(Activation('relu'))
model.add(Dropout(DROPOUT))

model.add(Dense(N_HIDDEN2))
model.add(Activation('relu'))
model.add(Dropout(DROPOUT))


model.add(Dense(N_HIDDEN3))
model.add(Activation('relu'))
model.add(Dropout(DROPOUT))

model.add(Dense(NB_CLASSES))
model.add(Activation('sigmoid'))
model.summary()



# Loss Train
#model.compile(loss='categorical_crossentropy',optimizer=OPTIMIZER,metrics=['accuracy'])
model.compile(loss="binary_crossentropy", optimizer=OPTIMIZER,metrics=["accuracy"])
history = model.fit(X_train, y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH,verbose=VERBOSE,
                    validation_split=VALIDATION_SPLIT)
# Test

score = model.evaluate(X_test, y_test, verbose=VERBOSE)
print("Test score:", score[0])
print('Test accuracy:', score[1])

In [ ]:
# list all data in history
print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
eeeeeeeeewrrpr

In [ ]:
from keras.models import load_model

model.save("/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/USE/vfl_model.h5")  # creates a HDF5 file 'my_model.h5'
#del model  # deletes the existing model

In [ ]:
# Import AI MODULES & FRAMEWORKS
from __future__ import division, print_function
from keras import backend as K
from keras.callbacks import ModelCheckpoint 
from keras.models import Sequential
from keras.layers.convolutional import Conv2D
#from keras.layers.convolutional import MaxPooling2D,AveragePooling2D
from keras.layers.pooling import AveragePooling2D,GlobalAveragePooling2D,MaxPooling2D,GlobalMaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense, Dropout 
#from keras_contrib
#from keras_contrib.layers.core import CosineDense
from keras.layers.advanced_activations import LeakyReLU
from keras.datasets import mnist
from keras.utils import np_utils
from keras.optimizers import SGD, RMSprop, Adam
from keras.layers import LSTM
from keras.layers.normalization import BatchNormalization
import numpy as np
import pylab as plt
import numpy as np
import matplotlib.pyplot as plt
import os 

from keras.initializers import TruncatedNormal

In [ ]:
# returns a compiled model
# identical to the previous one
model = load_model("/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/USE/vfl_model.h5")

In [ ]:
#SETTINGS##

#MODEL_DIR = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/" #over2.5
MODEL_DIR = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/hxa/"
MODEL_DIR2 = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/MOD/"

BATCH_SIZE = 5
VERBOSE = 1
OPTIMIZER = Adam()
VALIDATION_SPLIT=0.15
ROWS,COLS = 7, 3 # input image dimensions
INPUT_SHAPE = (1, ROWS, COLS)

count = 0
NB_EPOCH = 30
INITIAL_EPOCH = 0

In [ ]:
checkpoint = ModelCheckpoint( filepath=os.path.join(MODEL_DIR, "model-{epoch:02d}.h5"),save_best_only=True) 
history = model.fit(X_train, y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH,initial_epoch = INITIAL_EPOCH,verbose=VERBOSE,validation_split=VALIDATION_SPLIT,callbacks=[checkpoint])
score = model.evaluate(X_test, y_test, verbose=VERBOSE)

# save best model with
checkpoint = ModelCheckpoint( filepath=os.path.join(MODEL_DIR2, "model-{epoch:02d}.h5"),save_best_only=True)
#sleep(2)
print("Test score:", score[0])
print('Test accuracy:', score[1])
#print('Test accuracy percentage:', round(score[1]*100,3),'%')
#model.save('g8FT_model.h5')

In [ ]:
#model.save("/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/USE/vfl{}_model.h5".format(score[1]))

In [ ]:
# list all data in history
print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()